obstacle_range: 3.0
raytrace_range: 3.0

footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
#robot_radius: 0.105

inflation_radius: 0.25
cost_scaling_factor: 0.0
inflation_layer:
  enabled: true

map_type: costmap
track_unknown_space: false
lethal_cost_threshold: 100
observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}