local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.1  

  static_map: false  
  rolling_window: true
  # increase I think the local cost_map is too small
  width: 20 
  height: 20 
  resolution: 0.25
  
