warehouse_1:
  cell_size: 0.25
  grid_origin_x: -7
  grid_origin_y: -7
  grid_width: 14
  grid_height: 14
  locations:
    start:            [39, 40, 0]
    charging_station: [23, 29, 0]
    storage_area:     [59, 28, 0] 

warehouse_2:
  cell_size: 0.25
  grid_origin_x: -7
  grid_origin_y: -7
  grid_width: 14
  grid_height: 14
  locations:
    shelf_1:          [60, 58, 0]
    charging_station: [36, 48, 0]
    storage_area:     [44, 21, 0] 